spring:
  application:
    name: issue-tracker
  data:
    mongodb:
      uri: mongodb://test:secret@localhost/test?authSource=admin

#server:
#  ssl:
#    key-store: classpath:keystore/otus-spring-diploma_issue-tracker.p12
#    key-store-type: PKCS12
#    key-alias: otus-spring-diploma_issue-tracker
#    key-store-password: secret

mongobee:
  enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
