spring:
  application:
    name: issue-tracker
  data:
    mongodb:
      uri: mongodb://test:secret@localhost/test?authSource=admin

#server:
#  ssl:
#    key-store: classpath:keystore/otus-spring-diploma_issue-tracker.p12
#    key-store-type: PKCS12
#    key-alias: otus-spring-diploma_issue-tracker
#    key-store-password: secret

mongobee:
  enabled: true

security:
  keycloak:
    host: http://localhost:8180
    realm: Otus-Spring-Diploma
    client: otus-spring-diploma-client

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
