server:
  ssl:
    key-store: classpath:keystore/otus-spring-diploma_issue-tracker.p12
    key-store-type: PKCS12
    key-alias: otus-spring-diploma_issue-tracker
    key-store-password: secret

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://localhost/test

mongobee:
  enabled: true
